const mongoose=require("mongoose");
const userSchema = new mongoose.Schema(
    {
        "name":{
            type:String,
            required:true
        },
        "email":{
            type:String,
            required:true
        },
        "password":{
            type:String,
            required:true
        },
        "phoneNumber":{
            type:String,
            required:true,
        },
        "address":{
            type:[Object],
            required:false,
        },
        "productsPurchased":{
            type:[Object],
            required:false,
        },
        "productsInCart":{
            type:[Object],
            required:false,
        },
        "role":{
            type:String,
            default:"user",
            required:true,
        },
        "otp":{
            type:String,
            require:false
        },
        "expiry":{
            type:Date,
            required:false
        },
        "orderAwaitingPayment":{
            type:Object,
            required:false,
        }
    }
)

module.exports=mongoose.model("users",userSchema)